name: Deploy Express to Elastic Beanstalk

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Prepare deployment zip
        run: |
          zip -r app.zip . -x "node_modules/*" "*.git/*"

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # change to your region

      - name: Upload zip to S3
        run: |
          S3_BUCKET="${{ secrets.EB_S3_BUCKET }}"  # replace with your bucket
          aws s3 cp app.zip s3://$S3_BUCKET/app.zip

      - name: Create Elastic Beanstalk application version
        run: |
          APP_NAME="React Next Marketplace"
          VERSION_LABEL="v-$(date +%Y%m%d%H%M%S)"
          S3_BUCKET="my-eb-bucket"
          aws elasticbeanstalk create-application-version \
            --application-name $APP_NAME \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=app.zip

      - name: Update Elastic Beanstalk environment
        run: |
          APP_NAME="React Next Marketplace"
          ENV_NAME="ReactNextMarketplace-env"
          VERSION_LABEL=$(aws elasticbeanstalk describe-application-versions \
            --application-name $APP_NAME \
            --query "ApplicationVersions[-1].VersionLabel" \
            --output text)
          aws elasticbeanstalk update-environment \
            --environment-name $ENV_NAME \
            --version-label $VERSION_LABEL
